### ISSUE TITLE
Erro ao criar projeto com Postgres. 

### ISSUE THREAD

**Issue by getzleo** [VemtoOrg/vemto2-issues#56] opened 2024-04-02 16:57 UTC
É gerado um erro na aplicação, nova, quando configurado para utilizar Postgres.
Versão Vemto: 2.0.6

schema-reader Error: #0 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(151): Illuminate\Database\DatabaseManager->configuration('postgresql')VEMTO_EOL#1 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(93): Illuminate\Database\DatabaseManager->makeConnection('postgresql')VEMTO_EOL#2 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php(70): Illuminate\Database\DatabaseManager->connection()VEMTO_EOL#3 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): Illuminate\Database\DatabaseServiceProvider->Illuminate\Database\{closure}(Object(Illuminate\Foundation\Application), Array)VEMTO_EOL#4 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\Container\Container->build(Object(Closure))VEMTO_EOL#5 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\Container\Container->resolve('db.connection', Array, true)VEMTO_EOL#6 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\Foundation\Application->resolve('db.connection', Array)VEMTO_EOL#7 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Container\Container->make('db.connection', Array)VEMTO_EOL#8 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(1446): Illuminate\Foundation\Application->make('db.connection')VEMTO_EOL#9 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(67): Illuminate\Container\Container->offsetGet('db.connection')VEMTO_EOL#10 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(900): {closure}(Object(Illuminate\Foundation\Application), Array)VEMTO_EOL#11 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Illuminate\Container\Container->build(Object(Closure))VEMTO_EOL#12 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1026): Illuminate\Container\Container->resolve('db.schema', Array, true)VEMTO_EOL#13 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(723): Illuminate\Foundation\Application->resolve('db.schema', Array)VEMTO_EOL#14 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1011): Illuminate\Container\Container->make('db.schema', Array)VEMTO_EOL#15 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Container/Container.php(1446): Illuminate\Foundation\Application->make('db.schema')VEMTO_EOL#16 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(240): Illuminate\Container\Container->offsetGet('db.schema')VEMTO_EOL#17 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Support\Facades\Facade::resolveFacadeInstance('db.schema')VEMTO_EOL#18 /Users/lggil/Developer/Vemto/projeto1/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(351): Illuminate\Support\Facades\Facade::getFacadeRoot()VEMTO_EOL#19 /Users/lggil/Developer/Vemto/projeto1/database/migrations/0001_01_01_000000_create_users_table.php(14): Illuminate\Support\Facades\Facade::__callStatic('create', Array)VEMTO_EOL#20 [internal function]: Illuminate\Database\Migrations\Migration@anonymous->up()VEMTO_EOL#21 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke(Object(Illuminate\Database\Migrations\Migration@anonymous))VEMTO_EOL#22 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(77): MigrationDecoder->decode()VEMTO_EOL#23 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(107): {closure}()VEMTO_EOL#24 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(18): Vemto::execute('schema-reader', Object(Closure))VEMTO_EOL#25 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')VEMTO_EOL#26 {main}

**Comment by slzno** [comment] 2024-04-03 19:49
The problem is that it is putting `postgresql` as the driver and it should be `pgsql`, if you change it it will recognize the project.

**Comment by TiagoSilvaPereira** [comment] 2024-04-03 20:58
> The problem is that it is putting `postgresql` as the driver and it should be `pgsql`, if you change it it will recognize the project.

yeap, that's the problem... I'll fix this for the next version

**Comment by TiagoSilvaPereira** [comment] 2024-04-15 20:49
Fixed on 2.0.7

**Closed as completed by TiagoSilvaPereira** 2024-04-15 20:49 UTC
