### ISSUE TITLE
Vemto 2.0.7 returns to 2.0.6 after closing the app

### ISSUE THREAD

**Issue by LeonardoPessatti** [VemtoOrg/vemto2-issues#83] opened 2024-04-17 08:37 UTC
Even after removing appdata and program files folders, and reinstalling Vemto, it goes back to 2.0.6 after closing and opening again.

**Comment by TiagoSilvaPereira** [comment] 2024-04-17 13:34
Hi @LeonardoPessatti what SO are you using? How are you reinstalling it? Could you please give more details?

**Comment by LeonardoPessatti** [comment] 2024-04-17 20:17
I'm running Windows 11, and I was reinstalling by running the installer. 
When it reverted the version the first time, I uninstalled the 2.0.6 version through 'Programs and Resources' from Control Panel first, and installed 2.0.7 again.
When it reverted to 2.0.6 again, I tried uninstalling and manually deleting the Vemto folders on appdata, reinstalled and the problem persisted.
Then Vemto, despite installed, stop showing on programs and resources screen.

Maybe there's some folder which the installer doesn't overwrite? What folders Vemto creates/changes when installing? Maybe I can manually remove them all and see if it solves the problem.

**Comment by TiagoSilvaPereira** [comment] 2024-04-17 21:38
This is strange behavior. I'll investigate, as I never saw or heard about it happening. I'm uploading 2.0.8 now; let's see if the problem continues

**Comment by LeonardoPessatti** [comment] 2024-04-24 20:37
I had Vemto fixed in the taskbar and the problem happens while I was starting Vemto from there.
Once I started Vemto from its folder, the problem was gone.

**Comment by TiagoSilvaPereira** [comment] 2024-05-09 20:54
Hi @LeonardoPessatti, I tried to reproduce this bug without success. It might be a localized issue due to an isolated condition in your environment. I'm closing for now, but feel free to reopen it if necessary.

**Closed as completed by TiagoSilvaPereira** 2024-05-09 20:54 UTC
