### ISSUE TITLE
Permissions issues on macOS

### ISSUE THREAD

**Issue by MikeCraig418** [VemtoOrg/vemto2-issues#97] opened 2024-04-22 20:50 UTC
**Error Message:**  
(error) FAILED to execute command: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL1"

**Stack:**

```
Error: Command failed: "php" "/Applications/Vemto.app/Contents/Resources/static/VMTTL1"

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

**How to reproduce:**

1.  Start a new project (in Vemto)
2.  Add a model
3.  Add a corresponding Filament view
4.  Observe the error

**Expected behavior:**

> Code generation should work as expected.

**Actual behavior:**

> The Stack error above was received

**Additional context:**

This appears to be a permission issue.

In the Files Queue, I can see a number of files in the resources can not be generated due to Permission error.

Going into the project, I simply fix the permissions and the code generation works again.

```shell
➜  project ls -l resources 
total 0
ls: fts_read: Permission denied

➜  project find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;

➜  project ls -l
total 960
-rw-r--r--@   1 yo-mike  staff    4109 Apr  9 07:13 README.md
drwxr-xr-x@  10 yo-mike  staff     320 Apr 22 13:41 app
-rwxr-xr-x@   1 yo-mike  staff     350 Apr  9 07:13 artisan
drwxr-xr-x@   5 yo-mike  staff     160 Apr  9 07:13 bootstrap
-rw-r--r--@   1 yo-mike  staff    2181 Apr 22 12:57 composer.json
-rw-r--r--@   1 yo-mike  staff  378427 Apr 22 12:57 composer.lock
drwxr-xr-x@  15 yo-mike  staff     480 Apr 22 12:57 config
drwxr-xr-x@   7 yo-mike  staff     224 Apr 22 12:57 database
drwxr-xr-x@   3 yo-mike  staff      96 Apr 22 13:41 lang
drwxr-xr-x@ 129 yo-mike  staff    4128 Apr 22 12:57 node_modules
-rw-r--r--@   1 yo-mike  staff   72889 Apr 22 12:57 package-lock.json
-rw-r--r--@   1 yo-mike  staff     429 Apr 22 12:57 package.json
-rw-r--r--@   1 yo-mike  staff    1191 Apr  9 07:13 phpunit.xml
-rw-r--r--@   1 yo-mike  staff      93 Apr 22 12:57 postcss.config.js
drwxr-xr-x@   9 yo-mike  staff     288 Apr 22 12:57 public
drw-r--r--@   6 yo-mike  staff     192 Apr 22 12:57 resources
drwxr-xr-x@   6 yo-mike  staff     192 Apr 22 13:41 routes
drwxr-xr-x@   5 yo-mike  staff     160 Apr  9 07:13 storage
-rw-r--r--@   1 yo-mike  staff     656 Apr 22 12:57 tailwind.config.js
drwxr-xr-x@   5 yo-mike  staff     160 Apr  9 07:13 tests
drwxr-xr-x@  55 yo-mike  staff    1760 Apr 22 12:57 vendor
-rw-r--r--@   1 yo-mike  staff     310 Apr 22 12:57 vite.config.js
```

---

Vemto 2.0.8  
darwin 23.4.0  
Locale: en-US  
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment] 2024-04-23 14:38
Hi @yo-mike, thanks for reporting; I'll try to reproduce this bug. I don't know exactly why, but some people end up having permissions issues on macOS, but I can't reproduce them on my Mac.

**Comment by MikeCraig418** [comment] 2024-04-23 18:44
I have another new project I'll be working on over the next week. I'll see if I can recreate the issue.

**Comment by TiagoSilvaPereira** [comment] 2024-05-09 20:28
Adding useful info from https://github.com/TiagoSilvaPereira/vemto2-issues/issues/54

**Comment by TiagoSilvaPereira** [comment] 2024-05-09 20:54
Adding useful info from https://github.com/TiagoSilvaPereira/vemto2-issues/issues/52

**Comment by isaackearl** [comment] 2024-05-14 05:39
OK so I downloaded vemto 2.0.12 today and I'm plagued with permissions issues.  only way I can get anything to work is if I do chmod -R 777 <project name>.  It doesn't matter how I make the project... If I make it with vemto or scaffold myself and then try and connect to the folder.. either way it does something to the permissions where I can't do anything with the project.  I can't even revert changes using git because I get permissions denied errors.    Pretty frustrating experience.  I can't see anything weird about my permissions so I know this bug report doesn't help much.  Just wanted to say it's still happening on the latest version and I can't find a work around other then chmod -R 777

**Comment by isaackearl** [comment] 2024-05-14 05:58
@TiagoSilvaPereira It would be really nice if there was a database only option for vemto.  Right now I'm struggling to get the filament features etc working (because of the permissions issues I think), so it would be nice if I could enable a setting so I could just use it as a database schema scaffolding tool.

**Comment by TiagoSilvaPereira** [comment] 2024-05-14 15:34
@isaackearl, thanks for your suggestion. This option would be hard to develop because of the Vemto 2 architecture (it needs to boot the Laravel application to work). It would be easier to fix the permissions issue. I'm already trying to fix it. The problem is that I can't reproduce it on my MacOS; it just works here (and it also works for other people, so I still need to identify what specific on those environments is causing these issues). But I'm collecting a lot of feedback from people with this issue, and once I reproduce it, I'll fix it.

About this:

> Pretty frustrating experience

I'm sorry and will ask for a little patience. I'm doing my best to fix all the problems. I just need some time.

**Comment by TiagoSilvaPereira** [comment] 2024-05-14 15:37
@isaackearl about this:

> Pretty frustrating experience

I'm sorry and will ask for a little patience. I'm doing my best to fix all the problems. I just need some time.

**Comment by TiagoSilvaPereira** [comment] 2024-05-14 15:39
Adding usefult information from https://github.com/TiagoSilvaPereira/vemto2-issues/issues/134

**Comment by TiagoSilvaPereira** [comment] 2024-05-14 19:07
@isaackearl, does this problem happen when creating a project with Breeze instead of Jetstream?

**Comment by isaackearl** [comment] 2024-05-14 19:19
> @isaackearl, does this problem happen when creating a project with Breeze instead of Jetstream? 

It happens with both. Anytime I touch vemto to a new or existing project.

If I make a new project without using vemto, then everything works normally without any issues... But when I connect vemto to the project then I start having permission issues.

**Comment by TiagoSilvaPereira** [comment] 2024-05-14 19:23
Ok, thanks!

**Comment by TiagoSilvaPereira** [comment] 2024-05-15 19:19
I'm adding some information here. Tomorrow, after many tries, the error suddenly happened to me. But now all is working normally again. Vemto does not change permissions on the project's main folder, so I'm still not sure what is causing this error (also, it only happens on macOS, apparently).

I am still investigating.

**Comment by TiagoSilvaPereira** [comment] 2024-05-15 22:31
@yo-mike @isaackearl, please check the new version 2.0.13 if the problem persists. If it is still there, please send me some images or text information with the current folders and file permissions after creating a new project.

**Comment by TiagoSilvaPereira** [comment] 2024-05-16 18:20
Apparently, the problem has been fixed, according to reports in the issue https://github.com/TiagoSilvaPereira/vemto2-issues/issues/134

Waiting for confirmation. Grateful!

**Comment by MikeCraig418** [comment] 2024-05-16 20:08
Hi @TiagoSilvaPereira -- Honestly, I forgot about this issue. I don't think I've experienced anything since. I'll try again with the newest build and let you know if I see it pop up again.

> Just wanted to say it's still happening on the latest version and I can't find a work around other then chmod -R 777

@isaackearl You can try `sudo find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;` if you don't want to get too loosey-goosey.

**Comment by TiagoSilvaPereira** [comment] 2024-05-16 20:15
> Hi @TiagoSilvaPereira -- Honestly, I forgot about this issue. I don't think I've experienced anything since. I'll try again with the newest build and let you know if I see it pop up again.
> 
> > Just wanted to say it's still happening on the latest version and I can't find a work around other then chmod -R 777
> 
> @isaackearl You can try `sudo find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;` if you don't want to get too loosey-goosey.

Perfect, @yo-mike. Thanks! Vemto 2.0.13 will automatically execute chmod when creating files and folders and set the correct permissions (755 for folders and 644 for files). I'm not really sure, but it seems Nodejs had a bug when creating files or folders on macOS or Linux and setting incorrect permissions (and it seemed to occur randomly). So now, whenever Vemto creates a file or folder, it will apply the correct permissions to it.

**Comment by TiagoSilvaPereira** [comment] 2024-05-17 20:37
Closing as fixed. Please feel free to continue conversation if necessary

**Closed as completed by TiagoSilvaPereira** 2024-05-17 20:37 UTC
Labels: bug
