### ISSUE TITLE
schema-reader Error: Call to a member function compileTables() on null

### ISSUE THREAD

**Issue by silentpatrik** [VemtoOrg/vemto2-issues#36] opened 2024-03-18 03:51 UTC
**Project info**
Existing project in Laravel 10, nova 4.31, horizon, volt, livewire, folio, 3 custom packages, filament. No starter kit, no vue only folio and volt components + nova for some admin.

**Error Message:**
schema-reader Error: Call to a member function compileTables() on null

**Stack:**
```
schema-reader Error: #0 /home/user/Phpprojects/silentridge_io/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\Database\Schema\Builder->getTables()
#1 /home/user/Phpprojects/silentridge_io/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\Database\Schema\Builder->hasTable()
#2 /home/user/Phpprojects/packages/nova-v4.31.3/nova/database/migrations/2022_12_19_000000_create_field_attachments_table.php(16): Illuminate\Support\Facades\Facade::__callStatic()
#3 [internal function]: CreateFieldAttachmentsTable->up()
#4 phar:///tmp/.mount_Vemto-7GReEr/resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke()
#5 phar:///tmp/.mount_Vemto-7GReEr/resources/static/VMTTL1/index.php(77): MigrationDecoder->decode()
#6 phar:///tmp/.mount_Vemto-7GReEr/resources/static/VMTTL1/common/Vemto.php(107): {closure}()
#7 phar:///tmp/.mount_Vemto-7GReEr/resources/static/VMTTL1/index.php(18): Vemto::execute()
#8 /tmp/.mount_Vemto-7GReEr/resources/static/VMTTL1(15): require('...')
#9 {main}
```

---

Vemto 2.0.5
linux 6.6.10-76060610-generic
Locale: en-US
App version: 2.0.5

**Comment by TiagoSilvaPereira** [comment] 2024-03-19 17:00
Hi @silentpatrik thanks for reporting... I'm closing as it is duplicate of: https://github.com/TiagoSilvaPereira/vemto2-issues/issues/27

**Closed as completed by TiagoSilvaPereira** 2024-03-19 17:00 UTC

**Comment by silentpatrik** [comment] 2024-03-19 21:54
> Hi @silentpatrik thanks for reporting... I'm closing as it is duplicate of: #27

Yes, it is! Sorry for not checking properly!

**Comment by silentpatrik** [comment] 2024-03-21 18:56
@TiagoSilvaPereira I thought you wanted to know, in my case it was Laravel Nova causing the issue. Removing nova solved it.

**Comment by TiagoSilvaPereira** [comment] 2024-03-22 16:17
> @TiagoSilvaPereira I thought you wanted to know, in my case it was Laravel Nova causing the issue. Removing nova solved it.

Thanks bro!! Soon, this kind of problem will don't exist on Vemto anymore
