### ISSUE TITLE
Filmanet Resources stuck in Queue as Idle

### ISSUE THREAD

**Issue by adampatterson** [VemtoOrg/vemto2-issues#150] opened 2024-05-27 04:40 UTC
I was playing around with the app trying to assess it's capabilities and so far really like it.

I tried to add some simple Filament resources but they are all stuck as Idle.

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/31537/36034a67-883d-443b-ae9d-d3b25e0260df)

**Comment by TiagoSilvaPereira** [comment] 2024-05-27 12:57
@adampatterson the Filament resources stuck as Idle if you don't install Filament in the project (Vemto shows a modal asking you to install Filament before generating the code). It is necessary because Vemto needs to boot the whole Laravel application, and if it generates Filament classes without Filament being installed, Laravel will not boot correctly and Vemto may not work

**Comment by adampatterson** [comment] 2024-05-27 14:15
Humm, I created a new project and chose filament then. It did install Filament 3.2

I do have a Filament `AdminPanelProvider`, but that's all I noticed.

I also tried creating some CRUD pages and they didn't generate anything. 

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/31537/232ee4d5-72f5-4186-8db5-45211644a4ce)

**Comment by TiagoSilvaPereira** [comment] 2024-05-27 18:51
@adampatterson is this still on Idle state?

**Comment by adampatterson** [comment] 2024-05-28 01:22
@TiagoSilvaPereira yea it's been a day.

**Comment by TiagoSilvaPereira** [comment] 2024-05-28 14:31
@adampatterson, could you please record a video showing the entire process? I did not manage to reproduce this issue, so if you could provide more information, this would help a lot

**Comment by adampatterson** [comment] 2024-05-30 15:59
Hello @TiagoSilvaPereira  sure I can try to do that tonight, it's been a busy week :)

I am on the trial and it's probably got a few days left.

**Comment by adampatterson** [comment] 2024-05-31 14:16
@TiagoSilvaPereira   I recreated the project and feel silly.

1) I didn't know to click the play button, I sort of assumed it was to run unit tests. 
   - It doesn't help that I named the project Test
2) when I do it's telling me that it can't generate files on a trial but 
   - it says I have more than 15 tables but I only have 11

https://d.pr/v/7KFVWG

**Comment by TiagoSilvaPereira** [comment] 2024-05-31 18:41
Hi @adampatterson it accounts for all tables on your project, including the Laravel default tables (which you can see under the "Laravel" schema section). Could you please try with a smaller project where you can finish code generation and check if this work?

**Comment by adampatterson** [comment] 2024-05-31 20:14
@TiagoSilvaPereira  sute thing, I'll check my tables. I included users but I assume migration and jobs will also count so that could be what put me over.

**Comment by TiagoSilvaPereira** [comment] 2024-05-31 20:40
@adampatterson, that's perfect! Yes, it does account for all application tables, including the 8 tables generated by Laravel migrations. I want to change this behavior in the future, but I haven't had time yet. Best regards!

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/7a9e1a95-1b6d-4909-82ff-9cd76ec7db3c)

**Comment by adampatterson** [comment] 2024-06-02 02:07
I reduced the number of tables but my previous issue is causing problems.

I haven't change anything but always have a schema changes so the queues are still idle. 

https://github.com/TiagoSilvaPereira/vemto2-issues/issues/149

**Comment by TiagoSilvaPereira** [comment] 2024-06-05 15:48
@adampatterson closing as it seems to be resolved. Please feel free to reopen if necessary

**Closed as completed by TiagoSilvaPereira** 2024-06-05 15:48 UTC
