### ISSUE TITLE
(error) FAILED to execute command: "C:\xampp\php\php.exe" "C:\Users\Utilizador\AppData\Local\Programs\Vemto\resources\static\VMTTL1"

### ISSUE THREAD

**Issue by irafaelfurtado** [VemtoOrg/vemto2-issues#103] opened 2024-04-27 23:10 UTC
**Error Message:**
(error) FAILED to execute command: "C:\xampp\php\php.exe" "C:\Users\Utilizador\AppData\Local\Programs\Vemto\resources\static\VMTTL1"

**Stack:**
```
Error: Command failed: "C:\xampp\php\php.exe" "C:\Users\Utilizador\AppData\Local\Programs\Vemto\resources\static\VMTTL1"
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: localhost:9003 (through xdebug.client_host/xdebug.client_port).
PHP Fatal error:  Cannot redeclare App\Models\Status::moviments() in C:\projects\example588\app\Models\Status.php on line 29

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.8
win32 10.0.22631
Locale: pt-PT
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment] 2024-04-29 18:14
Hi @irafaelfurtado seems the problem is happening on the Status.php model, could you please check what is happening with this class?

```
PHP Fatal error:  Cannot redeclare App\Models\Status::moviments() in C:\projects\example588\app\Models\Status.php on line 29
```

**Comment by TiagoSilvaPereira** [comment] 2024-05-07 18:55
@irafaelfurtado any news on checking the model code?

**Comment by TiagoSilvaPereira** [comment] 2024-05-09 20:00
Closing as it does not seem to be a Vemto bug (it seems the problem is under application code, most specifically in the Status.php model)

**Closed as completed by TiagoSilvaPereira** 2024-05-09 20:00 UTC
