### ISSUE TITLE
Basic install with Jetstream Teams - InvalidArgumentException - view Welcome not found

### ISSUE THREAD

**Issue by jpetit601** [VemtoOrg/vemto2-issues#54] opened 2024-04-02 15:27 UTC
I tried the most basic install without adding any tables or CRUD but selecting Jetstream and teams. I tried this with MySQL and SQLite. It runs the initial script without errors. I then test in the server and view it where it reports InvalidArgumentException - view welcome not found

![error](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/112421371/86df2c06-4b40-4ef6-a4a0-289fa249c5da)

**Comment by TiagoSilvaPereira** [comment] 2024-04-02 15:39
Thanks for reporting. I'm adding @nicollassilva to check what is happening

**Comment by nicollassilva** [comment] 2024-04-02 19:17
Hello @jpetit601, I installed some projects locally here and I couldn't reproduce your error, can you give me more information about your environment?

**Comment by jpetit601** [comment] 2024-04-02 22:30
I am on a Mac Studio - M1 Max - plenty of ram. Older OS - Monterey 12.6. 

- php 8.3.3
- npm 8.13.2
- node 18.6

**Comment by jpetit601** [comment] 2024-04-04 03:03
I have found that the resouces folder on multiple projects when generated with Jetstream is not being given permission for me to access it - very odd. This is means no views are savable there and thus the no Welcome message. 
<img width="251" alt="image" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/112421371/38f2ce17-76f9-4faf-941f-8e3c72cb3077">

If I set my permissions for these folders to read and write in the finder - I can see the files and so can Laravel - the app works! (to a point - it runs into other errors like not finding a menu partial - but that may also be a permissions issue)

When I choose Breeze to generate, all works fine.

**Comment by TiagoSilvaPereira** [comment] 2024-04-04 14:37
@jpetit601 Thanks for reporting, I'll try to reproduce this bug to fix it on a future version... for now, I recommend manually changing the folder permissions with ```chmod 755```

**Comment by TiagoSilvaPereira** [comment] 2024-04-15 20:48
Hi @jpetit601, did chmod 755 work?

**Comment by isaackearl** [comment] 2024-05-06 07:41
I was getting same issue and chmod 755 did NOT work for me.  I had to do chmod 777 before it actually started working, but I don't know what other security ramifications that will have... @TiagoSilvaPereira

**Comment by TiagoSilvaPereira** [comment] 2024-05-06 15:45
Hi @isaackearl, maybe it is creating the project in a folder that Vemto doesn't have writing permissions in (a protected folder, for example). Could you please check this? Would it be possible to record a video so that I can reproduce the issue?

**Comment by TiagoSilvaPereira** [comment] 2024-05-09 20:29
Closing. We'll continue Permissions discussion on #97

**Closed as completed by TiagoSilvaPereira** 2024-05-09 20:29 UTC
