### ISSUE TITLE
schema-reader Error: Call to a member function compileDisableForeignKeyConstraints() on null

### ISSUE THREAD

**Issue by jjjrmy** [VemtoOrg/vemto2-issues#9] opened 2024-03-12 01:26 UTC
I get this in my Schema log

**Comment by TiagoSilvaPereira** [comment] 2024-03-12 14:13
@jjjrmy does this function compileDisableForeignKeyConstraints exists on your code? Seems Vemto cannot read your project due to a problem in the code. Could you please try with a new project and check if the error happens?

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 14:41
@jjjrmy, does this error keep occurring with 2.0.4?

**Comment by jjjrmy** [comment] 2024-03-14 21:14
Yes it's still occuring.

I'm not sure where that code exists but we are using `Schema::disableForeignKeyConstraints();` in some migrations, and that looks like it's calling that from within the Laravel framework code.

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 23:22
> Yes it's still occuring.
> 
> I'm not sure where that code exists but we are using `Schema::disableForeignKeyConstraints();` in some migrations, and that looks like it's calling that from within the Laravel framework code.

Perfect, I'll try to reproduce. Thanks!!

**Comment by TiagoSilvaPereira** [comment] 2024-04-15 20:34
Fixed on 2.0.7 by using Database Schema Reader mode

**Closed as completed by TiagoSilvaPereira** 2024-04-15 20:34 UTC
