### ISSUE TITLE
(error) FAILED to execute command: ""/php"" artisan storage:link

### ISSUE THREAD

**Issue by sbritz** [VemtoOrg/vemto2-issues#166] opened 2024-06-07 06:58 UTC
**Error Message:**
(error) FAILED to execute command: ""/Users/stefanbritz/Library/Application Support/Herd/bin//php"" artisan storage:link
    |> /bin/sh: /Users/stefanbritz/Library/Application: No such file or directory

**Stack:**
```
Error: Command failed: ""/Users/stefanbritz/Library/Application Support/Herd/bin//php"" artisan storage:link
/bin/sh: /Users/stefanbritz/Library/Application: No such file or directory

    at ChildProcess.exithandler (node:child_process:407:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

---

Vemto 2.0.17
darwin 23.5.0
Locale: de
App version: 2.0.17

**Comment by TiagoSilvaPereira** [comment] 2024-06-07 14:03
Hi @sbritz thanks for reporting... seems the problem is the space on your directory "Application Support". Could you please check if the problem happens in a folder without spaces in the name?

**Comment by sbritz** [comment] 2024-07-09 20:43
hi, sorry for my late answer. I use Herd and I cannot find a way to change the Folder. Do you have a tip for me?

**Comment by TiagoSilvaPereira** [comment] 2024-07-10 13:29
Hi, @sbritz. Could you please check if this error still occurs on 2.0.23?

**Comment by TiagoSilvaPereira** [comment] 2024-07-10 15:10
Ah, @sbritz, could you please share your Vemto settings screen?

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/89a049eb-ee24-422c-8618-39447e864545)

I just checked and it works with spaces. Maybe your settings have an extra quote like this?

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/d8474a5a-30f0-4bce-89b4-67608ba6b6d7)

I added extra quotes and the same issue happened here (it is not necessary to add quotes because Vemto already does this internally)

**Comment by sbritz** [comment] 2024-07-11 09:50
hi Tiago,
my settings path-fields are both empty now, and it works fine. No idea why. But your new vemto-version seems to find the correct paths automatically.
<img width="721" alt="Bildschirmfoto 2024-07-11 um 11 34 48" src="https://github.com/TiagoSilvaPereira/vemto2-issues/assets/25327081/a7319bf0-600c-4ebe-9fdb-6180d0d7b718">

**Comment by TiagoSilvaPereira** [comment] 2024-07-11 12:39
Perfect @sbritz I'm closing for now, but please feel free to reopen if necessary

**Closed as completed by TiagoSilvaPereira** 2024-07-11 12:39 UTC
