### ISSUE TITLE
[Performance] MacOs lagg

### ISSUE THREAD

**Issue by chris-mackie** [VemtoOrg/vemto2-issues#10] opened 2024-03-12 11:04 UTC
MacOS Monterey 12.7.1
Mac Pro (Late 2013)
12-Core Xeon E5
64GB ram

When using Vemto, theres is a considerable delay and time when waiting for the cursor to respond. Also, GPU usage is quite high. Getting the below in the GPU sample and no way to disable hardware acceleration:

CoreSymbolication warning: fde.addrRange.location 0x10c08ff08 isn't in the the __TEXT segment [0x10c182000 - 0x00031000)

**Comment by TiagoSilvaPereira** [comment] 2024-03-12 14:12
Hi @chris-mackie is this a big project or a new one? How many tables do you have in this project?

Also, I don't recommend disabling GPU. Vemto uses Electron and it is GPU accelerated.

**Comment by chris-mackie** [comment] 2024-03-12 14:14
Hi @TiagoSilvaPereira Its a new one with only 2 small tables.

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 14:42
@chris-mackie would it be possible to record a video? I'm trying to reproduce without success (I have a MacBook M1 8gb and it runs well here)

**Comment by chris-mackie** [comment] 2024-03-14 14:47
https://github.com/TiagoSilvaPereira/vemto2-issues/assets/700079/dd7a9716-b229-4b62-a5ba-64091c9cccb1

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 15:03
This is strange; I'll try to understand what is happening. Maybe it's because I'm compiling x64 from an arm64 Mac?

**Comment by Abdifatahz** [comment] 2024-03-14 18:27
I also encountered that lag on my Mac M1

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 20:03
> I also encountered that lag on my Mac M1

@Abdifatahz thanks for reporting, I'm trying to identify what is happening. I'm algo on a M1 and it runs OK

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 22:47
@chris-mackie I need to apologize, seems Electron has problems with GPU on macOS. I'll launch a new version with GPU disabled

**Comment by TiagoSilvaPereira** [comment] 2024-03-14 23:20
@chris-mackie @Abdifatahz Could you please try 2.0.5? I turned off GPU acceleration on macOS. It seems Chromium has some issues with those computers' GPUs.

Also, if the issue persists, please try turning off the code changes detector on Project Settings:

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/f2819a3a-11bd-4a59-98b8-16f9475f24b7)

**Comment by Abdifatahz** [comment] 2024-03-15 00:32
It works great, when I enable that checkbox.

**Comment by chris-mackie** [comment] 2024-03-15 11:13
Same here. When the code change detection is disabled the lag is gone. Shame to have it disabled but its a fix for now. Thanks @TiagoSilvaPereira

**Comment by TiagoSilvaPereira** [comment] 2024-03-15 13:28
@chris-mackie @Abdifatahz perfect, now I know what to fix. Thanks!

**Comment by james2doyle** [comment] 2024-03-27 00:00
Just did this on my M1 as well and all the lag was gone immediately

**Comment by MikeCraig418** [comment] 2024-04-11 18:57
Jumping in the mix :) I'm using Vemto 2 on a new project and I noticed the M1 Lag straight away.

**Edit:**

~Are you able to compile an ARM version for Apple's M1, M2, and M3 processors?~

The ARM version is much more performant... Thank you

**Comment by TiagoSilvaPereira** [comment] 2024-04-12 13:26
Hi @yo-mike, did you need to disable the code changes detector? Or it works well with this enabled?

**Comment by MikeCraig418** [comment] 2024-04-15 15:31
Hey @TiagoSilvaPereira - The ARM build is better than the original build I installed w/ 2.0.

The latest ARM build does slow down, especially as the table schemas grow and get bigger. Disabling the code changes detector works quite well.

How often do the code changes poll/scan?

**Comment by TiagoSilvaPereira** [comment] 2024-04-15 15:56
@yo-mike thanks for the information, the next Vemto version will solve this as I am using native macOS fsevents to watch the files changes

**Comment by TiagoSilvaPereira** [comment] 2024-04-15 20:35
@chris-mackie @james2doyle @Abdifatahz @yo-mike I have good news!! I just launched Vemto 2.0.7 which uses native macOS fsevents to handle file changes. On our tests it completely solved performance issues. I'll just wait for your feedback to close the issue. Thanks!!!

**Comment by chris-mackie** [comment] 2024-04-15 20:37
@TiagoSilvaPereira amazing! will give it a test tomorrow and let you know.

**Comment by chris-mackie** [comment] 2024-04-16 10:46
@TiagoSilvaPereira I'm getting `schema-reader Error: The [web] middleware group has not been defined.` on an existing project with:

- Laravel 11 
- Jetstream with inertia/Vue

**Comment by TiagoSilvaPereira** [comment] 2024-04-16 14:27
Hi @chris-mackie does this error happen with new projects? Or only with this specific project? Is it possible to open a new issue showing how we can reproduce this error?

**Comment by chris-mackie** [comment] 2024-04-17 11:33
@TiagoSilvaPereira New projects too when using inertia and vuejs.

**Comment by TiagoSilvaPereira** [comment] 2024-04-17 13:42
@chris-mackie hmm ok thanks, I'll check this. Probably Vue applications doesn't have the web middleware and this is causing the error (I think the schema reader is booting the application trying to load routes, but this is not necessary and I'll remove this in the next version)

**Comment by chris-mackie** [comment] 2024-04-17 13:46
@TiagoSilvaPereira Might be related to L11 removing the Middleware and providers?

**Comment by TiagoSilvaPereira** [comment] 2024-04-17 14:15
@chris-mackie I'll check if this is the case. Thanks for your help bro

**Closed as completed** 2024-04-22 18:01 UTC
Labels: bug, important
