### ISSUE TITLE
Can't create table vemto_epos.products

### ISSUE THREAD

**Issue by jsthind** [VemtoOrg/vemto2-issues#168] opened 2024-06-17 11:18 UTC
**Error Message:**
schema-reader-db Error: SQLSTATE[HY000]: General error: 1005 Can't create table `vemto_epos`.`products` (errno: 150 "Foreign key constraint is incorrectly formed") (Connection: vemto_db_connection, SQL: alter table `products` add constraint `products_store_category_id_foreign` foreign key (`store_category_id`) references `store_categories` (`id`) on delete cascade on update cascade)

**Stack:**
```
schema-reader-db Error: #0 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(767): Illuminate\Database\Connection->runQueryCallback('alter table `pr...', Array, Object(Closure))
#1 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('alter table `pr...', Array, Object(Closure))
#2 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(109): Illuminate\Database\Connection->statement('alter table `pr...')
#3 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(418): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(357): Illuminate\Database\Schema\Builder->create('products', Object(Closure))
#6 C:\apps\UniformServer\vhosts\epos\backend\database\migrations\2024_06_17_110202_004_create_products_table.php(15): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#7 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(476): Illuminate\Database\Migrations\Migration@anonymous->up()
#8 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(402): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#9 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(411): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#10 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(212): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#11 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(743): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#12 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(212): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2024_06_17_1102...', Object(Closure))
#13 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('C:\\apps\\Uniform...', 1, false)
#14 C:\apps\UniformServer\vhosts\epos\backend\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#15 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(114): Illuminate\Database\Migrations\Migrator->run('C:\\apps\\Uniform...')
#16 phar://C:/Program Files/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#17 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#18 C:\Program Files\Vemto\resources\static\VMTTL2(14): require('phar://C:/Progr...')
#19 {main}
```

---

Vemto 2.0.21
win32 10.0.22631
Locale: en-US
App version: 2.0.21

**Comment by TiagoSilvaPereira** [comment] 2024-06-17 14:45
Hi @jsthind please check your foreign keys. It seems you have a foreign key with an incorrect format (if you created a foreign one manually, please check if it corresponds with the related column). It is common, for example, to create a signed foreign column and try to reference an unsigned column

**Comment by jsthind** [comment] 2024-06-17 15:28
Hi @TiagoSilvaPereira, the foreign keys were generated automatically as a part of the model relationship that I created using Vemto. Moreover, I am unable to open the project now. Each time I try to open the project, I get the above error message.

**Comment by TiagoSilvaPereira** [comment] 2024-06-17 15:31
@jsthind ok, I need to check this. Could you please check what is incorrect on your migrations? For example, if a generated foreign key does not match the referenced column (also, by fixing this manually, you'll be able to open the project again)

**Comment by jsthind** [comment] 2024-06-17 15:50
So I looked into the vemto_**** database and the issue is that table being referenced by the foreign key does not exist at all. The **products** table has a column _store_category_id_ which would link to **store_categories** table.

But the **store_categories** table does not exist in the database

**Comment by TiagoSilvaPereira** [comment] 2024-06-17 15:51
hmm ok, did you remove this table or something like that?

**Comment by jsthind** [comment] 2024-06-17 15:52
No, I didn't event look at the vemto_*** database until you asked for further details.

How do I get the project to open? I can't proceed beyond the error screen.

**Comment by TiagoSilvaPereira** [comment] 2024-06-17 15:54
Is the migration order incorrect? For example, is the foreign key being created before the referenced table?

It would not be possible to open the project before fixing the migrations (because Vemto needs to run the migrations to read the schema)

**Comment by jsthind** [comment] 2024-06-17 16:01
_Is the migration order incorrect? For example, is the foreign key being created before the referenced table?_
Yes, that seems to be the issue.

**Comment by TiagoSilvaPereira** [comment] 2024-06-17 16:03
Okay, in this case, I recommend manually fixing the migrations. Also, would it be possible to reproduce your steps so that I can identify what went wrong and fix it in future Vemto versions?

**Comment by TiagoSilvaPereira** [comment] 2024-06-20 14:33
@jsthind hi there, could you please give instructions on how I can reproduce this issue?

**Comment by TiagoSilvaPereira** [comment] 2024-06-28 17:19
@jsthind closing due to lack of details, please feel free to reopen if necessary

**Closed as completed by TiagoSilvaPereira** 2024-06-28 17:19 UTC
